### PR TITLE
Wired up S3 buckets but needs a get query to pull User. Also wired up…

### PR DESCRIPTION
**Pull request by RogerMReyes**
… Verification Login, Signup, and Verify. Must Test all to verify opertaion work correctly

### CODE REVIEW

**Review by zaratr — APPROVED** [review]
after I manually changed you request in the manifest, it works like butter on toast!

**Comment by zaratr** [comment]
I approved but with one change in my review in manifest..

**Comment by zaratr** [comment]
Needs further testing with Amplify because we cant tell if this works correctly. It 100% should however work in signed in user.

**Review by AbdulahiMohamud — APPROVED** [review]
LGTM

**Pull request merged**
